language: ruby
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script:
  - bundle exec rubocop
  - bundle exec rake spec
branches:
  only:
    - master
