source 'https://rubygems.org'

gem 'kaminari'
gem 'http_accept_language'

group :development do
  gem 'bullet'
  gem 'rack-mini-profiler'
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :development, :test do
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'guard-rubocop'
  gem 'guard-brakeman'
  gem 'guard-yarn'
  gem 'spring-commands-rspec'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'libnotify', require: false
  gem 'growl', require: false

  gem 'factory_bot_rails'
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
  gem 'ci_reporter_rspec', require: false
  gem 'rubocop'
  gem 'brakeman'

  gem 'byebug'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'

  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'tapp'
  gem 'awesome_print'
end

group :test do
  gem 'webmock', require: false
end
